function haversineM(lat1, lon1, lat2, lon2) {
  const R = 6371000
  const φ1 = lat1 * Math.PI / 180
  const φ2 = lat2 * Math.PI / 180
  const dφ = (lat2 - lat1) * Math.PI / 180
  const dλ = (lon2 - lon1) * Math.PI / 180
  const a = Math.sin(dφ / 2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin(dλ / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
}

export function calcLength(towers) {
  let total = 0
  for (let i = 1; i < towers.length; i++) {
    total += haversineM(towers[i - 1].lat, towers[i - 1].lon, towers[i].lat, towers[i].lon)
  }
  return total
}

export function formatLength(meters) {
  return meters >= 1000
    ? `${(meters / 1000).toFixed(2)} km`
    : `${Math.round(meters)} m`
}

export function generateKML(towers, fromIdx, toIdx, lineName, startNumber = 1) {
  const lo = Math.min(fromIdx, toIdx)
  const hi = Math.max(fromIdx, toIdx)
  const slice = towers.slice(lo, hi + 1)
  const ordered = fromIdx > toIdx ? [...slice].reverse() : slice
  const selected = ordered.map((t, i) => ({
    ...t,
    towerNumber: startNumber + i,
  }))
  const from = selected[0]
  const to = selected[selected.length - 1]
  const lengthStr = formatLength(calcLength(selected))

  const coordinates = selected.map(t => `${t.lon},${t.lat},0`).join('\n\t\t\t\t')

  const placemarks = selected
    .map(
      t => `
\t<Placemark>
\t\t<name>Tower ${t.towerNumber}</name>
\t\t<description><![CDATA[
\t\t\t<b>Tower Number:</b> ${t.towerNumber}<br/>
\t\t\t<b>OSM Node ID:</b> ${t.osmId}<br/>
\t\t\t<b>Latitude:</b> ${t.lat.toFixed(7)}<br/>
\t\t\t<b>Longitude:</b> ${t.lon.toFixed(7)}
\t\t]]></description>
\t\t<styleUrl>#towerStyle</styleUrl>
\t\t<Point>
\t\t\t<coordinates>${t.lon},${t.lat},0</coordinates>
\t\t</Point>
\t</Placemark>`
    )
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
\t<name>${lineName} — Tower ${from.towerNumber} to Tower ${to.towerNumber}</name>
\t<description>Generated by सर्जनम् | ${selected.length} towers | Length: ${lengthStr} | ${lineName}</description>

\t<Style id="lineStyle">
\t\t<LineStyle>
\t\t\t<color>ffee8800</color>
\t\t\t<width>4</width>
\t\t</LineStyle>
\t</Style>

\t<Style id="towerStyle">
\t\t<IconStyle>
\t\t\t<color>ff0000ff</color>
\t\t\t<scale>0.9</scale>
\t\t\t<Icon>
\t\t\t\t<href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
\t\t\t</Icon>
\t\t</IconStyle>
\t\t<LabelStyle>
\t\t\t<scale>0.7</scale>
\t\t</LabelStyle>
\t</Style>

\t<Placemark>
\t\t<name>${lineName} (${lengthStr})</name>
\t\t<styleUrl>#lineStyle</styleUrl>
\t\t<LineString>
\t\t\t<tessellate>1</tessellate>
\t\t\t<coordinates>
\t\t\t\t${coordinates}
\t\t\t</coordinates>
\t\t</LineString>
\t</Placemark>
${placemarks}
</Document>
</kml>`
}

export function generateCSV(towers, fromIdx, toIdx, lineName, startNumber = 1) {
  const lo = Math.min(fromIdx, toIdx)
  const hi = Math.max(fromIdx, toIdx)
  const slice = towers.slice(lo, hi + 1)
  const ordered = fromIdx > toIdx ? [...slice].reverse() : slice
  const selected = ordered.map((t, i) => ({
    ...t,
    towerNumber: startNumber + i,
  }))

  const esc = (v) => {
    const s = String(v ?? '')
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }

  const header = ['Tower Number', 'OSM Node ID', 'Latitude', 'Longitude', 'Line Name']
  const rows = selected.map((t) => [
    t.towerNumber,
    t.osmId,
    t.lat.toFixed(7),
    t.lon.toFixed(7),
    lineName,
  ])

  return [header, ...rows].map((r) => r.map(esc).join(',')).join('\r\n')
}

function download(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadKML(content, filename) {
  download(content, filename, 'application/vnd.google-earth.kml+xml')
}

export function downloadCSV(content, filename) {
  download(content, filename, 'text/csv;charset=utf-8')
}
